name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
  
    - name: Install Dependencies
      run: yarn install
      working-directory: ./chain-thought
  
    - name: Build Project
      run: yarn build
      working-directory: ./chain-thought
      env:
        CI: false
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        publish_dir: chain-thought/dist # Replace with your build directory
